# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d85fada506f57b5ef4091be2d110c6c409571c80b87ee6650ae6926a3f3ead1639249e87825008965c5a301f5f3297b399da91bd26493371f5f09bf90aecd3a

test:
  secret_key_base: 725b261f090e70cda15da3e4b45de69a39c50742249190575572fe2f188a383e05ebc3a1f57c8f388fd6452ae15971135966327b3a8a7202bbe665df25bc5ffc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
